
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace max_model_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 24> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 12, column 2 to column 9)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 13, column 2 to column 9)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 14, column 2 to column 9)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 15, column 2 to column 9)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 17, column 2 to column 12)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 18, column 2 to column 22)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 29, column 2 to column 172)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 31, column 2 to column 151)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 25, column 2 to column 25)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 26, column 2 to column 135)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 2, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 3, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 4, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 4, column 2 to column 25)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 5, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 5, column 2 to column 26)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 6, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 6, column 2 to column 30)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 7, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 7, column 2 to column 26)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 9, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 9, column 2 to column 14)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/max_model.stan', line 31, column 8 to column 9)"};



class max_model_model final : public model_base_crtp<max_model_model> {

 private:
  int N;
  int M;
  Eigen::Matrix<double, -1, 1> num_build500__;
  Eigen::Matrix<double, -1, 1> mean_fa_ratio__;
  Eigen::Matrix<double, -1, 1> min_distance_park__;
  Eigen::Matrix<double, -1, 1> num_trees_50m__;
  Eigen::Matrix<double, -1, 1> y__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> num_build500{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mean_fa_ratio{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> min_distance_park{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> num_trees_50m{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> y{nullptr, 0};
 
 public:
  ~max_model_model() { }
  
  inline std::string model_name() const final { return "max_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  max_model_model(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "max_model_model_namespace::max_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 11;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 11;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 11;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 12;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 12;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 12;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 13;
      validate_non_negative_index("num_build500", "N", N);
      current_statement__ = 14;
      context__.validate_dims("data initialization","num_build500","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      num_build500__ = Eigen::Matrix<double, -1, 1>(N);
      new (&num_build500) Eigen::Map<Eigen::Matrix<double, -1, 1>>(num_build500__.data(), N);
      
      
      {
        std::vector<local_scalar_t__> num_build500_flat__;
        current_statement__ = 14;
        num_build500_flat__ = context__.vals_r("num_build500");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 14;
          assign(num_build500, num_build500_flat__[(pos__ - 1)],
            "assigning variable num_build500", index_uni(sym1__));
          current_statement__ = 14;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 15;
      validate_non_negative_index("mean_fa_ratio", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","mean_fa_ratio","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      mean_fa_ratio__ = Eigen::Matrix<double, -1, 1>(N);
      new (&mean_fa_ratio) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mean_fa_ratio__.data(), N);
      
      
      {
        std::vector<local_scalar_t__> mean_fa_ratio_flat__;
        current_statement__ = 16;
        mean_fa_ratio_flat__ = context__.vals_r("mean_fa_ratio");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 16;
          assign(mean_fa_ratio, mean_fa_ratio_flat__[(pos__ - 1)],
            "assigning variable mean_fa_ratio", index_uni(sym1__));
          current_statement__ = 16;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 17;
      validate_non_negative_index("min_distance_park", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","min_distance_park",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      min_distance_park__ = Eigen::Matrix<double, -1, 1>(N);
      new (&min_distance_park) Eigen::Map<Eigen::Matrix<double, -1, 1>>(min_distance_park__.data(), N);
      
      
      {
        std::vector<local_scalar_t__> min_distance_park_flat__;
        current_statement__ = 18;
        min_distance_park_flat__ = context__.vals_r("min_distance_park");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 18;
          assign(min_distance_park, min_distance_park_flat__[(pos__ - 1)],
            "assigning variable min_distance_park", index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      validate_non_negative_index("num_trees_50m", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization","num_trees_50m","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      num_trees_50m__ = Eigen::Matrix<double, -1, 1>(N);
      new (&num_trees_50m) Eigen::Map<Eigen::Matrix<double, -1, 1>>(num_trees_50m__.data(), N);
      
      
      {
        std::vector<local_scalar_t__> num_trees_50m_flat__;
        current_statement__ = 20;
        num_trees_50m_flat__ = context__.vals_r("num_trees_50m");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 20;
          assign(num_trees_50m, num_trees_50m_flat__[(pos__ - 1)],
            "assigning variable num_trees_50m", index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      y__ = Eigen::Matrix<double, -1, 1>(N);
      new (&y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(y__.data(), N);
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 22;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 22;
          assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", index_uni(sym1__));
          current_statement__ = 22;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      validate_non_negative_index("y_rep", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "max_model_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ a;
      a = DUMMY_VAR__;
      
      current_statement__ = 1;
      a = in__.template read<local_scalar_t__>();
      local_scalar_t__ b;
      b = DUMMY_VAR__;
      
      current_statement__ = 2;
      b = in__.template read<local_scalar_t__>();
      local_scalar_t__ c;
      c = DUMMY_VAR__;
      
      current_statement__ = 3;
      c = in__.template read<local_scalar_t__>();
      local_scalar_t__ d;
      d = DUMMY_VAR__;
      
      current_statement__ = 4;
      d = in__.template read<local_scalar_t__>();
      local_scalar_t__ bias;
      bias = DUMMY_VAR__;
      
      current_statement__ = 5;
      bias = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 6;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      {
        current_statement__ = 9;
        lp_accum__.add(inv_gamma_lpdf<propto__>(sigma, 1, 1));
        current_statement__ = 10;
        lp_accum__.add(
          normal_lpdf<propto__>(rvalue(y, "y", index_min_max(1, M)),
            add(
              add(
                add(
                  add(
                    multiply(a,
                      rvalue(num_build500, "num_build500",
                        index_min_max(1, M))),
                    multiply(b,
                      rvalue(mean_fa_ratio, "mean_fa_ratio",
                        index_min_max(1, M)))),
                  multiply(c,
                    rvalue(min_distance_park, "min_distance_park",
                      index_min_max(1, M)))),
                multiply(d,
                  rvalue(num_trees_50m, "num_trees_50m", index_min_max(1, M)))),
              bias), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "max_model_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double a;
      a = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      a = in__.template read<local_scalar_t__>();
      double b;
      b = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      b = in__.template read<local_scalar_t__>();
      double c;
      c = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      c = in__.template read<local_scalar_t__>();
      double d;
      d = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      d = in__.template read<local_scalar_t__>();
      double bias;
      bias = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      bias = in__.template read<local_scalar_t__>();
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      out__.write(a);
      out__.write(b);
      out__.write(c);
      out__.write(d);
      out__.write(bias);
      out__.write(sigma);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double log_p;
      log_p = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      log_p = normal_lpdf<false>(rvalue(y, "y", index_min_max((M + 1), N)),
                add(
                  add(
                    add(
                      add(
                        multiply(a,
                          rvalue(num_build500, "num_build500",
                            index_min_max((M + 1), N))),
                        multiply(b,
                          rvalue(mean_fa_ratio, "mean_fa_ratio",
                            index_min_max((M + 1), N)))),
                      multiply(c,
                        rvalue(min_distance_park, "min_distance_park",
                          index_min_max((M + 1), N)))),
                    multiply(d,
                      rvalue(num_trees_50m, "num_trees_50m",
                        index_min_max((M + 1), N)))), bias), sigma);
      std::vector<double> y_rep;
      y_rep = std::vector<double>(M, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 8;
      assign(y_rep,
        normal_rng(
          add(
            add(
              add(
                add(
                  multiply(a,
                    rvalue(num_build500, "num_build500", index_min_max(1, M))),
                  multiply(b,
                    rvalue(mean_fa_ratio, "mean_fa_ratio",
                      index_min_max(1, M)))),
                multiply(c,
                  rvalue(min_distance_park, "min_distance_park",
                    index_min_max(1, M)))),
              multiply(d,
                rvalue(num_trees_50m, "num_trees_50m", index_min_max(1, M)))),
            bias), sigma, base_rng__), "assigning variable y_rep");
      out__.write(log_p);
      out__.write(y_rep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      local_scalar_t__ a;
      a = DUMMY_VAR__;
      
      a = in__.read<local_scalar_t__>();
      out__.write(a);
      local_scalar_t__ b;
      b = DUMMY_VAR__;
      
      b = in__.read<local_scalar_t__>();
      out__.write(b);
      local_scalar_t__ c;
      c = DUMMY_VAR__;
      
      c = in__.read<local_scalar_t__>();
      out__.write(c);
      local_scalar_t__ d;
      d = DUMMY_VAR__;
      
      d = in__.read<local_scalar_t__>();
      out__.write(d);
      local_scalar_t__ bias;
      bias = DUMMY_VAR__;
      
      bias = in__.read<local_scalar_t__>();
      out__.write(bias);
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"a", "b", "c", "d", "bias", "sigma",
      "log_p", "y_rep"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(M)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "a");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "d");
    param_names__.emplace_back(std::string() + "bias");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "log_p");
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "a");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "d");
    param_names__.emplace_back(std::string() + "bias");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "log_p");
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bias\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_p\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(M) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bias\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_p\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(M) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (1 + M);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (1 + M);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 6> names__{"a", "b", "c", "d", "bias",
      "sigma"};
      const std::array<Eigen::Index, 6> constrain_param_sizes__{1, 1, 
       1, 1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = max_model_model_namespace::max_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return max_model_model_namespace::profiles__;
}

#endif


