
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace time_sensitive_model_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 38> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 18, column 2 to column 16)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 19, column 2 to column 22)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 20, column 2 to column 20)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 21, column 2 to column 20)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 34, column 2 to column 21)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 36, column 4 to column 54)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 35, column 17 to line 37, column 3)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 35, column 2 to line 37, column 3)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 24, column 2 to column 25)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 27, column 4 to column 40)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 26, column 2 to line 27, column 40)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 30, column 4 to column 48)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 29, column 17 to line 31, column 3)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 29, column 2 to line 31, column 3)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 2, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 3, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 4, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 5, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 6, column 14 to column 15)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 6, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 6, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 7, column 14 to column 15)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 7, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 7, column 2 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 10, column 2 to column 16)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 11, column 16 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 11, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 11, column 2 to column 30)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 14, column 16 to column 17)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 14, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 14, column 2 to column 30)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 18, column 9 to column 10)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 18, column 11 to column 12)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 19, column 13 to column 14)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 20, column 13 to column 14)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 34, column 18 to column 19)",
 " (in '/Users/sotiriskaragounis/git/UHInyc/time_sensitive_model.stan', line 34, column 9 to column 10)"};



class time_sensitive_model_model final : public model_base_crtp<time_sensitive_model_model> {

 private:
  int N;
  int M;
  int H;
  int K;
  std::vector<Eigen::Matrix<double, -1, 1>> X;
  std::vector<Eigen::Matrix<double, -1, 1>> y;
  int T;
  std::vector<Eigen::Matrix<double, -1, 1>> X_t;
  std::vector<Eigen::Matrix<double, -1, 1>> y_t; 
  
 
 public:
  ~time_sensitive_model_model() { }
  
  inline std::string model_name() const final { return "time_sensitive_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  time_sensitive_model_model(stan::io::var_context& context__,
                             unsigned int random_seed__ = 0,
                             std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "time_sensitive_model_model_namespace::time_sensitive_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 15;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 15;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 15;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 16;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 16;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 17;
      context__.validate_dims("data initialization","H","int",
           std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      
      current_statement__ = 17;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 17;
      check_greater_or_equal(function__, "H", H, 0);
      current_statement__ = 18;
      context__.validate_dims("data initialization","K","int",
           std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 18;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 18;
      check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 19;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 20;
      validate_non_negative_index("X", "K", K);
      current_statement__ = 21;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>(N),
            static_cast<size_t>(K)});
      X = std::vector<Eigen::Matrix<double, -1, 1>>(N, Eigen::Matrix<double, -1, 1>(K));
      
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 21;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 21;
        pos__ = 1;
        current_statement__ = 21;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 21;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 21;
            assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 21;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 22;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 23;
      validate_non_negative_index("y", "H", H);
      current_statement__ = 24;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(N),
            static_cast<size_t>(H)});
      y = std::vector<Eigen::Matrix<double, -1, 1>>(N, Eigen::Matrix<double, -1, 1>(H));
      
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 24;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 24;
        pos__ = 1;
        current_statement__ = 24;
        for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
          current_statement__ = 24;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 24;
            assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 24;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 25;
      T = std::numeric_limits<int>::min();
      
      current_statement__ = 25;
      T = (N - M);
      current_statement__ = 26;
      validate_non_negative_index("X_t", "M", M);
      current_statement__ = 27;
      validate_non_negative_index("X_t", "K", K);
      current_statement__ = 28;
      X_t = std::vector<Eigen::Matrix<double, -1, 1>>(M, Eigen::Matrix<double, -1, 1>(K));
      stan::math::fill(X_t, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 28;
      assign(X_t, rvalue(X, "X", index_min_max(1, M), index_omni()),
        "assigning variable X_t");
      current_statement__ = 29;
      validate_non_negative_index("y_t", "M", M);
      current_statement__ = 30;
      validate_non_negative_index("y_t", "H", H);
      current_statement__ = 31;
      y_t = std::vector<Eigen::Matrix<double, -1, 1>>(M, Eigen::Matrix<double, -1, 1>(H));
      stan::math::fill(y_t, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 31;
      assign(y_t, rvalue(y, "y", index_min_max(1, M), index_omni()),
        "assigning variable y_t");
      current_statement__ = 32;
      validate_non_negative_index("b", "H", H);
      current_statement__ = 33;
      validate_non_negative_index("b", "K", K);
      current_statement__ = 34;
      validate_non_negative_index("Sigma", "H", H);
      current_statement__ = 34;
      validate_non_negative_index("Sigma", "H", H);
      current_statement__ = 35;
      validate_non_negative_index("Eta", "K", K);
      current_statement__ = 35;
      validate_non_negative_index("Eta", "K", K);
      current_statement__ = 36;
      validate_non_negative_index("y_rep", "M", M);
      current_statement__ = 37;
      validate_non_negative_index("y_rep", "H", H);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (H * K) + (H + ((H * (H - 1)) / 2))
       + (K + ((K * (K - 1)) / 2)) + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "time_sensitive_model_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, -1> b;
      b = Eigen::Matrix<local_scalar_t__, -1, -1>(H, K);
      stan::math::fill(b, DUMMY_VAR__);
      
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(H, K);
      Eigen::Matrix<local_scalar_t__, -1, -1> Sigma;
      Sigma = Eigen::Matrix<local_scalar_t__, -1, -1>(H, H);
      stan::math::fill(Sigma, DUMMY_VAR__);
      
      current_statement__ = 2;
      Sigma = in__.template read_constrain_cov_matrix<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
                lp__, H);
      Eigen::Matrix<local_scalar_t__, -1, -1> Eta;
      Eta = Eigen::Matrix<local_scalar_t__, -1, -1>(K, K);
      stan::math::fill(Eta, DUMMY_VAR__);
      
      current_statement__ = 3;
      Eta = in__.template read_constrain_cov_matrix<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
              lp__, K);
      local_scalar_t__ rho;
      rho = DUMMY_VAR__;
      
      current_statement__ = 4;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      {
        current_statement__ = 9;
        lp_accum__.add(
          normal_lpdf<propto__>(rvalue(b, "b", index_uni(1), index_omni()),
            0, rho));
        current_statement__ = 11;
        for (int i = 2; i <= H; ++i) {
          current_statement__ = 10;
          lp_accum__.add(
            multi_normal_lpdf<propto__>(
              rvalue(b, "b", index_uni(i), index_omni()),
              rvalue(b, "b", index_uni((i - 1)), index_omni()), Eta));
        }
        current_statement__ = 14;
        for (int i = 1; i <= M; ++i) {
          current_statement__ = 12;
          lp_accum__.add(
            multi_normal_lpdf<propto__>(
              rvalue(y_t, "y_t", index_uni(i), index_omni()),
              multiply(b, rvalue(X_t, "X_t", index_uni(i), index_omni())),
              Sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "time_sensitive_model_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, -1> b;
      b = Eigen::Matrix<double, -1, -1>(H, K);
      stan::math::fill(b, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(H, K);
      Eigen::Matrix<double, -1, -1> Sigma;
      Sigma = Eigen::Matrix<double, -1, -1>(H, H);
      stan::math::fill(Sigma, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      Sigma = in__.template read_constrain_cov_matrix<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
                lp__, H);
      Eigen::Matrix<double, -1, -1> Eta;
      Eta = Eigen::Matrix<double, -1, -1>(K, K);
      stan::math::fill(Eta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      Eta = in__.template read_constrain_cov_matrix<Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(
              lp__, K);
      double rho;
      rho = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      out__.write(b);
      out__.write(Sigma);
      out__.write(Eta);
      out__.write(rho);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<Eigen::Matrix<double, -1, 1>> y_rep;
      y_rep = std::vector<Eigen::Matrix<double, -1, 1>>(M, Eigen::Matrix<double, -1, 1>(H));
      stan::math::fill(y_rep, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 8;
      for (int i = 1; i <= M; ++i) {
        current_statement__ = 6;
        assign(y_rep,
          multi_normal_rng(
            multiply(b, rvalue(X_t, "X_t", index_uni(i), index_omni())),
            Sigma, base_rng__),
          "assigning variable y_rep", index_uni(i), index_omni());
      }
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          out__.write(y_rep[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, -1> b;
      b = Eigen::Matrix<local_scalar_t__, -1, -1>(H, K);
      stan::math::fill(b, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          assign(b, in__.read<local_scalar_t__>(),
            "assigning variable b", index_uni(sym2__), index_uni(sym1__));
        }
      }
      out__.write(b);
      Eigen::Matrix<local_scalar_t__, -1, -1> Sigma;
      Sigma = Eigen::Matrix<local_scalar_t__, -1, -1>(H, H);
      stan::math::fill(Sigma, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          assign(Sigma, in__.read<local_scalar_t__>(),
            "assigning variable Sigma", index_uni(sym2__), index_uni(sym1__));
        }
      }
      out__.write_free_cov_matrix(Sigma);
      Eigen::Matrix<local_scalar_t__, -1, -1> Eta;
      Eta = Eigen::Matrix<local_scalar_t__, -1, -1>(K, K);
      stan::math::fill(Eta, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          assign(Eta, in__.read<local_scalar_t__>(),
            "assigning variable Eta", index_uni(sym2__), index_uni(sym1__));
        }
      }
      out__.write_free_cov_matrix(Eta);
      local_scalar_t__ rho;
      rho = DUMMY_VAR__;
      
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, rho);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"b", "Sigma", "Eta", "rho", "y_rep"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(H)
                                                                   ,
                                                                   static_cast<size_t>(K)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(H), static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(K)},
      std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(M), static_cast<size_t>(H)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "Sigma" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "Eta" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    param_names__.emplace_back(std::string() + "rho");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= (H + ((H * (H - 1)) / 2)); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "Sigma" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= (K + ((K * (K - 1)) / 2)); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "Eta" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "rho");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(H) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"Sigma\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(H) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"Eta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(M) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(H) + "}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(H) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"Sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((H + ((H * (H - 1)) / 2))) + "},\"block\":\"parameters\"},{\"name\":\"Eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K + ((K * (K - 1)) / 2))) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(M) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(H) + "}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((H * K) + (H * H)) + (K * K)) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (M * H);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((H * K) + (H * H)) + (K * K)) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (M * H);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 4> names__{"b", "Sigma", "Eta", "rho"
      };
      const std::array<Eigen::Index, 4> constrain_param_sizes__{(H * K),
       (H * H), (K * K), 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = time_sensitive_model_model_namespace::time_sensitive_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return time_sensitive_model_model_namespace::profiles__;
}

#endif


